
import './globals.css'

import { Inter } from 'next/font/google'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-[#F5F5F5]">
        <div className="relative h-screen">
          <Header />
          <div>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}